# Generated by Django 4.1 on 2022-09-06 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoice_tags_invoice_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company_logo',
        ),
    ]
